### ISSUE TITLE
Exclude Directory

### ISSUE THREAD

**Issue by albertofilice** [granlem/docker-volume-sync#3]
Hi,

Is it possible to esclude a directory from backup, for example /wp-content/cache ?

Best Regards

**Comment by granlem** [comment]
Sorry for the late answer...
I think that should be possible with the ADDITIONAL_OPTIONS environment variable when unison supports it. 
Unison(SYNC_CLIENT) gets called by:
`args = SYNC_CLIENT + ADDITIONAL_OPTIONS + [sync_source] + [sync_target]`

If the issue is still current. Please write back, then I'll try to find a concrete solution for this.
